name: rpi4_images
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        IMG-NAME: [BigLinux]
        DEVICE: [rpi4]
        # EDITION: [gnome,kde-plasma,mate,minimal,sway,xfce]
        EDITION: [kde-plasma]
        BRANCH: [stable]
    steps:
      - id: time
        uses: boredland/get-time-action@2.0.0
        with:
          format: 'YYYY-MM-DD_HH-mm'
          
      - id: name
        shell: bash
        run: |
          echo "name=$(echo ${{ matrix.img-name }}" | sed -e 's/\(.*\)/\L\1/') >> $GITHUB_OUTPUT
          
      - id: image-build
        uses: BigLinux-Package-Build/build-iso-arm@main
        with:
          img-name: ${{ matrix.img-name }}
          name: ${{ steps.name.outputs.name }}
          device: ${{ matrix.device }}
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          version: ${{ steps.time.outputs.time }}
          # overlay-repo: 
          #gpg-key: ${{ secrets.CI_GPG_SECRET }}
          #gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          
      - name: Release assets
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          name: Release ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
          files: |
            ${{ env.FILE_PATH }}
            ${{ env.FILE_SHA1 }}
            ${{ env.FILE_TORRENT }}
            ${{ env.FILE_PKG }}
            #${{ env.FILE_SIG }}
